name: conditional workflow

on: [push]

jobs:
  hello-world:
    if: github.repository == 'HandMadeMayo/test'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run: echo "Hello World!"
  bye-dude:
    runs-on: ubuntu-latest
    steps:
      - name: "Bye Dude"
        run: echo "Bye Dude!"