name: Job Dependency Test

on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo "I am needed for test2!"

  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - name: test2
        run: echo "I really need test1 for this to work!"