name: "Multi Event Trigger Test"

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: "Echo GH Info"
              run:
                echo "REF is $GITHUB_REF"
                echo "Job ID is $GITHUB_JOB"
                echo "Action is $GITHUB_ACTION"
                echo "Actor is $GITHUB_ACTOR"
