name: "Webhook Test"

on:
    repository_dispatch:
        types:
            - webhook

jobs:
    respond-to-dispatch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Run a script
              run: echo "This event is a $GITHUB_EVENT_NAME"